name: Static analysis

on:
  push:
  pull_request:

jobs:
  static-analysis:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup luarocks
        run: sudo apt install -y luarocks

      - name: Setup luacheck
        run: luarocks --local install luacheck

      - run: echo $(luarocks path --lr-bin) >> $GITHUB_PATH

      - name: Run luacheck
        run: luacheck .

      - run: luarocks lint luzer-scm-1.rockspec
